[package]
name = "chap"
version = "2.2.2"
edition = "2021"
description = "Chap is an easy to learn, interpretive, scripting language written in Rust"
license = "GPL-3.0"
readme = "README.md"
# documentation = "https://docs.rs/chap" # if not set docs.rs will generate one and put it in place 
homepage = "https://crates.io/crates/chap"
repository = "https://github.com/persian-tools/chap"
categories = ["wasm", "command-line-interface", "compilers"]
keywords = ["programming", "language", "scripting", "eval", "dynamic"]
include = ["src/**/*.rs", "Cargo.toml", "LICENSE", "README.md", "Logo.png"]

[lib]
name = "chap"
path = "src/lib.rs"

[[bin]]
name = "chap"
path = "src/main.rs"


[dependencies]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rustyline = "12.0.0"
rand = "0.8.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
overflow-checks=false
panic = "abort"
