use std::collections::{BTreeSet, HashMap, HashSet};
use std::fmt::Write;

use crate::common::data_type::DataType;
use crate::common::errors::{ChapError, Result};
use crate::common::executable::ExecutableLine;
use crate::common::param::Param;

const PRELUDE: &str = r#"/* Generated by chap to C compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>

typedef enum { T_INT, T_FLOAT, T_BOOL, T_STR } Type;

typedef struct {
    Type t;
    long long i;
    double f;
    int b;
    char* s;
} CV;

__attribute__((unused)) static CV cv_int(long long x) { CV v = {T_INT, x, 0.0, 0, NULL}; return v; }
__attribute__((unused)) static CV cv_flt(double x) { CV v = {T_FLOAT, 0, x, 0, NULL}; return v; }
__attribute__((unused)) static CV cv_bool(int x) { CV v = {T_BOOL, 0, 0.0, x, NULL}; return v; }
__attribute__((unused)) static CV cv_str_take(char* p) { CV v = {T_STR, 0, 0.0, 0, p}; return v; }

__attribute__((unused)) static CV cv_str(const char* x) {
    char* p = malloc(strlen(x) + 1);
    strcpy(p, x);
    return cv_str_take(p);
}

/* chap prints floats like rust does, %g is close enough for simple values */
__attribute__((unused)) static char* cv_to_string(CV v) {
    char buf[64];
    switch (v.t) {
        case T_INT: sprintf(buf, "%lld", v.i); break;
        case T_FLOAT: sprintf(buf, "%g", v.f); break;
        case T_BOOL: strcpy(buf, v.b ? "true" : "false"); break;
        case T_STR: strcpy(buf, v.s); break;
        default: strcpy(buf, ""); break;
    }
    return strdup(buf);
}

__attribute__((unused)) static double cv_num(CV v) {
    return v.t == T_INT ? (double)v.i : v.f;
}

__attribute__((unused)) static int cv_eq(CV a, CV b) {
    if (a.t != b.t) return 0;
    switch (a.t) {
        case T_INT: return a.i == b.i;
        case T_FLOAT: return a.f == b.f;
        case T_BOOL: return a.b == b.b;
        case T_STR: return strcmp(a.s, b.s) == 0;
        default: return 0;
    }
}

__attribute__((unused)) static CV cv_mod(CV a, CV b) {
    if (a.t == T_FLOAT || b.t == T_FLOAT) return cv_flt(fmod(cv_num(a), cv_num(b)));
    return cv_int(a.i % b.i);
}

__attribute__((unused)) static CV cv_toint(CV v) {
    if (v.t == T_INT) return v;
    if (v.t == T_FLOAT) return cv_int((long long)v.f);
    return cv_int(strtoll(v.s, NULL, 10));
}

/* joins n args with sep */
__attribute__((unused)) static char* cv_join(int n, va_list ap, const char* sep) {
    size_t cap = 64, len = 0;
    char* out = malloc(cap);
    out[0] = '\0';
    for (int k = 0; k < n; k++) {
        CV v = va_arg(ap, CV);
        char* s = cv_to_string(v);
        size_t sl = strlen(s), sepl = k ? strlen(sep) : 0;
        size_t need = len + sl + sepl + 1;
        while (cap < need) { cap *= 2; out = realloc(out, cap); }
        if (k) strcat(out, sep);
        strcat(out, s);
        free(s);
        len += sl + sepl;
    }
    return out;
}

__attribute__((unused)) static void chap_print(int n, ...) {
    va_list ap;
    va_start(ap, n);
    char* joined = cv_join(n, ap, ", ");
    va_end(ap);
    printf("%s\n", joined);
    free(joined);
}

__attribute__((unused)) static CV cv_concat(int n, ...) {
    va_list ap;
    va_start(ap, n);
    char* joined = cv_join(n, ap, "");
    va_end(ap);
    return cv_str_take(joined);
}

int main(void) {
"#;

/// normalize function name the same way builtin_function::closure_gen does
fn normalize(function_name: &str) -> String {
    function_name.to_lowercase().replace([' ', '_', '?'], "")
}

fn cname(name: &str) -> String {
    let mut result = String::from("v_");
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            result.push(c);
        } else {
            result.push('_');
        }
    }
    result
}

fn escape_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(c),
        }
    }
    result
}

fn err(line_number: u32, msg: String) -> ChapError {
    ChapError::static_analyzer_with_msg(line_number, msg)
}

/// turn a param into a C expression producing a CV
fn expr(param: &Param) -> Result<String> {
    Ok(match param {
        Param::Value(DataType::Int(i)) => format!("cv_int({}LL)", i),
        Param::Value(DataType::Float(f)) => format!("cv_flt({:?})", f),
        Param::Value(DataType::Bool(b)) => format!("cv_bool({})", *b as i32),
        Param::Value(DataType::String(s)) => format!("cv_str(\"{}\")", escape_string(s)),
        Param::Value(value) => {
            return Err(err(
                0,
                format!(
                    "the 2c compiler does not support this type yet: {}",
                    value.type_name()
                ),
            ))
        }
        Param::Variable(name) => cname(name),
        Param::Tag(tag, _) => {
            return Err(err(0, format!("unexpected tag @{} in value position", tag)))
        }
    })
}

pub fn generate(executables: &[ExecutableLine]) -> Result<String> {
    let names: Vec<String> = executables
        .iter()
        .map(|e| normalize(&e.function_name))
        .collect();

    // collect variables
    let mut vars: BTreeSet<String> = BTreeSet::new();
    for ex in executables {
        if let Some(output) = &ex.output_var {
            vars.insert(cname(output));
        }
        for param in &ex.params {
            if let Param::Variable(v) = param {
                vars.insert(cname(v));
            }
        }
    }

    // map tag name -> executable index (labels)
    let mut tags: HashMap<&str, usize> = HashMap::new();
    for (i, ex) in executables.iter().enumerate() {
        if names[i] == "newtag" {
            match ex.params.first() {
                Some(Param::Tag(tag, _)) => {
                    tags.insert(tag.as_str(), i);
                }
                _ => {
                    return Err(err(
                        ex.line_number,
                        "error while creating a tag".to_string(),
                    ))
                }
            }
        }
    }

    let target_of = |ex: &ExecutableLine| -> Result<usize> {
        match ex.params.first() {
            Some(Param::Tag(tag, _)) => match tags.get(tag.as_str()) {
                Some(i) => Ok(*i),
                None => Err(err(ex.line_number, format!("cant find tag: {}", tag))),
            },
            _ => Err(err(
                ex.line_number,
                "function jump needs a tag for first params".to_string(),
            )),
        }
    };

    // indexes which get a C label because some jump points at them
    let mut targets: HashSet<usize> = HashSet::new();
    for (i, name) in names.iter().enumerate() {
        if matches!(name.as_str(), "jump" | "jumpifnot" | "jeq" | "jneq") {
            targets.insert(target_of(&executables[i])?);
        }
    }

    // body
    let mut body = String::new();
    for v in &vars {
        writeln!(&mut body, "    CV {} = {{T_INT, 0, 0.0, 0, NULL}};", v).unwrap();
    }

    for (i, ex) in executables.iter().enumerate() {
        if targets.contains(&i) {
            writeln!(&mut body, "L{}:;", i).unwrap();
        }
        let statement = statement(ex, &names[i], &target_of)?;
        if !statement.is_empty() {
            writeln!(&mut body, "    {}", statement).unwrap();
        }
    }
    body.push_str("    return 0;\n}\n");

    let mut c_code = String::from(PRELUDE);
    c_code.push_str(&body);
    Ok(c_code)
}

fn statement(
    ex: &ExecutableLine,
    name: &str,
    target_of: &dyn Fn(&ExecutableLine) -> Result<usize>,
) -> Result<String> {
    let params = &ex.params;
    // chap semantics: a function result without output variable gets printed
    let assign_to = |value: String| -> String {
        match &ex.output_var {
            Some(output) => format!("{} = {};", cname(output), value),
            None => format!("chap_print(1, {});", value),
        }
    };
    let args = |from: usize| -> Result<Vec<String>> {
        params[from..]
            .iter()
            .map(expr)
            .collect::<Result<Vec<String>>>()
    };

    Ok(match name {
        "assign" => {
            let value = match params.first() {
                Some(p) => expr(p)?,
                None => {
                    return Err(err(
                        ex.line_number,
                        "assign function needs one input param".to_string(),
                    ))
                }
            };
            match &ex.output_var {
                Some(output) => format!("{} = {};", cname(output), value),
                None => {
                    return Err(err(
                        ex.line_number,
                        "assign function needs output".to_string(),
                    ))
                }
            }
        }
        "newtag" => String::new(), // handled by label emission

        "jump" => format!("goto L{};", target_of(ex)?),
        "jumpifnot" => {
            let tag = target_of(ex)?;
            let cond = args(1)?.into_iter().next();
            match cond {
                Some(cond) => format!("if (!({}).b) goto L{};", cond, tag),
                None => {
                    return Err(err(
                        ex.line_number,
                        "jump_if_not function needs bool as second param".to_string(),
                    ))
                }
            }
        }
        "jeq" | "jumpifequal" => {
            let tag = target_of(ex)?;
            let a = args(1)?; // [p1, p2]
            if a.len() != 2 {
                return Err(err(
                    ex.line_number,
                    "jump_if_equal needs two comparable params".to_string(),
                ));
            }
            format!("if (cv_eq({}, {})) goto L{};", a[0], a[1], tag)
        }
        "jneq" | "jumpifnotequal" => {
            let tag = target_of(ex)?;
            let a = args(1)?;
            if a.len() != 2 {
                return Err(err(
                    ex.line_number,
                    "jump_if_not_equal needs two comparable params".to_string(),
                ));
            }
            format!("if (!cv_eq({}, {})) goto L{};", a[0], a[1], tag)
        }

        "print" | "show" | "stdout" => {
            let a = args(0)?;
            format!(
                "chap_print({}{});",
                a.len(),
                a.into_iter().fold(String::new(), |acc, x| acc + ", " + &x)
            )
        }
        "concat" | "cat" => {
            let a = args(0)?;
            assign_to(format!(
                "cv_concat({}{})",
                a.len(),
                a.into_iter().fold(String::new(), |acc, x| acc + ", " + &x)
            ))
        }

        "increase" | "inc" => match params.first() {
            Some(Param::Variable(v)) => format!("{}.i += 1;", cname(v)),
            _ => {
                return Err(err(
                    ex.line_number,
                    "increase function need one variable".to_string(),
                ))
            }
        },

        "modulus" | "mod" => {
            let a = args(0)?;
            assign_to(format!("cv_mod({}, {})", a[0], a[1]))
        }
        "sqrt" | "squareroot" => {
            let a = args(0)?;
            assign_to(format!("cv_flt(sqrt(cv_num({})))", a[0]))
        }
        "toint" => {
            let a = args(0)?;
            assign_to(format!("cv_toint({})", a[0]))
        }
        "lt" | "lessthan" => {
            let a = args(0)?;
            assign_to(format!("cv_bool(cv_num({}) < cv_num({}))", a[0], a[1]))
        }

        "exit" | "quit" | "kill" | "end" => "return 0;".to_string(),

        _ => {
            return Err(err(
                ex.line_number,
                format!(
                    "the 2c compiler does not support this function yet: {}",
                    ex.function_name
                ),
            ))
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn assign_and_print() {
        let c_code = super::super::compile_to_c("10 -> $a\n$a").unwrap();
        assert!(c_code.contains("v_a = cv_int(10LL);"));
        assert!(c_code.contains("chap_print(1, v_a);"));
        assert!(c_code.ends_with("    return 0;\n}\n"));
    }

    #[test]
    fn jumps_become_gotos() {
        let c_code =
            super::super::compile_to_c("@loop\n@is, $i -> jump_if_not\n@end -> jump\n@is\n@end")
                .unwrap();
        assert!(c_code.contains("L3:;")); // label for @is
        assert!(c_code.contains("L4:;")); // label for @end
        assert!(c_code.contains("if (!(v_i).b) goto L3;")); // jump_if_not to @is
        assert!(c_code.contains("goto L4;")); // jump to @end
    }

    #[test]
    fn unknown_function_is_error() {
        assert!(super::super::compile_to_c("$a -> not_a_function").is_err());
    }

    #[test]
    fn unsupported_value_types_are_error() {
        assert!(super::super::compile_to_c("[1,2] -> $l").is_err());
    }
}
